[package]
name = "sturdystreamdeck"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.203", features = ["derive", "serde_derive"] }
tokio = { version = "1.38.0", features = ["full"] }
axum = { version = "0.6.20", features = ["tracing", "ws", "macros", "headers"] }
axum-extra = "0.7.7"
cargo-watch = "8.4.0"
futures = "0.3.28"
futures-util = "0.3.28"
regex = "1.10.2"
tokio-tungstenite = "0.20.0"
tower = { version = "0.4.13", features = ["full", "tokio"] }
tower-http = { version = "0.4.3", features = ["full", "trace"] }
tracing = "0.1.37"
tracing-subscriber = "0.3.17"
serde_json = "1.0.120"
